/*RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY 
THE HIGHEST SCORE FIRST*/


/*
SELECT *
FROM customers
ORDER BY Score DESC*/

/*RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY 
THE LOWEST SCORE FIRST*/

SELECT * 
FROM customers
ORDER BY score ASC
